---
book_repo: pivotal-cf/docs-book-tippo
layout_repo: pivotal-cf/docs-layout-repo

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: 1.7
  changelog_href: http://docs.pivotal.io/pivotalcf/pcf-release-notes/
  local_header_img: /images/cloud_rings.png
  local_header_title: Pivotal Cloud Foundry
public_host: hello

sections:
- repository:
    name: pivotal-cf/docs-tippo
  directory: pcf-automation
  subnav_template: pcf-automation_subnav.erb
  dependent_sections:
  - repository:
      name: pivotal-cf/pcf-installer
    no-docs: true

book_title: Platform Automation for PCF Documentation (Alpha)
