---
book_repo: pivotal-cf/docs-book-platform-automation
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'edge'

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

feedback_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-platform-automation
    ref: develop
  directory: pcf-automation/unreleased
  subnav_template: pcf-automation_subnav_develop.erb
  product_info:
    use_local_header: true
    latest_stable_version: alpha
    changelog_href: https://docs-platform-automation.cfapps.io/pcf-automation/pipeline-reference.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Platform Automation
    search_placeholder: Search Platform Automation
    url_prefix: pcf-automation/unreleased
    local_product_version: "ersion: Unreleased"
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs-pcf-staging.cfapps.io/pcf-automation/alpha
        display_name: Alpha
      - url_prefix: http://docs-pcf-staging.cfapps.io/pcf-automation/unreleased
        display_name: Unreleased (Preview)
  dependent_sections:
  - repository:
      name: pivotal-cf/platform-automation
      ref: develop
    no-docs: true

book_title: Platform Automation for PCF Documentation (Alpha)
